"use client";

import AssessmentPage from "./assessment";

/* Legacy prototype retained temporarily for source-history readability.
 * It is excluded from the compiled application; the live experience is AssessmentPage.
type Trait = "fire" | "thunder" | "gravity" | "time" | "judgment";
type Answer = { text: string; traits: Partial<Record<Trait, number>> };
type Question = { eyebrow: string; title: string; note?: string; answers: Answer[] };
type ResultProfile = { grade: string; gradeLabel: string; score: number; spell: string; spellNumber: string; spellType: string; spellDescription: string; character: string; characterTag: string; characterDescription: string; dominant: Trait };

const questions: Question[] = [
  { eyebrow: "01 / 血统直觉", title: "第一次走进陌生的古老遗迹，你会先做什么？", note: "选择更接近你真实反应的一项。", answers: [
    { text: "点亮周围，确认所有出口", traits: { fire: 2, judgment: 1 } }, { text: "站在原地，先观察环境的变化", traits: { time: 2, gravity: 1 } }, { text: "找到最高处，俯瞰整座遗迹", traits: { thunder: 2, fire: 1 } }, { text: "触碰墙面，试着感受它留下的信息", traits: { judgment: 2, time: 1 } },
  ] },
  { eyebrow: "02 / 临界时刻", title: "当队友犯错，危险正在逼近，你会怎么做？", answers: [
    { text: "挡在最前面，把危险引到自己身上", traits: { fire: 2, gravity: 1 } }, { text: "让所有人停下，重新排布行动顺序", traits: { time: 2, gravity: 1 } }, { text: "在一瞬间抓住破绽，直接反击", traits: { thunder: 2, fire: 1 } }, { text: "先判断谁还值得信任，再决定出手", traits: { judgment: 2, time: 1 } },
  ] },
  { eyebrow: "03 / 元素回响", title: "哪一种力量感最让你感到熟悉？", answers: [
    { text: "灼热：燃烧、爆裂、把沉默撕开", traits: { fire: 3 } }, { text: "雷鸣：速度、决断、落下即终结", traits: { thunder: 3 } }, { text: "重力：秩序、压迫、让万物归位", traits: { gravity: 3 } }, { text: "时间：停顿、预见、在缝隙里改变结果", traits: { time: 3 } },
  ] },
  { eyebrow: "04 / 意志强度", title: "如果你拥有一次改变局势的机会，你更想改变什么？", answers: [
    { text: "让敌人付出无法忽视的代价", traits: { fire: 1, thunder: 2 } }, { text: "让所有人停止互相伤害", traits: { gravity: 2, judgment: 1 } }, { text: "让某个已经失去的人重新回来", traits: { time: 2, judgment: 1 } }, { text: "让真相再也无法被隐藏", traits: { judgment: 3 } },
  ] },
  { eyebrow: "05 / 领域偏好", title: "你愿意把自己的力量集中在哪里？", answers: [
    { text: "近身五米：短促、炽烈、一次定胜负", traits: { fire: 2, thunder: 1 } }, { text: "一整片空间：让所有人感到我的存在", traits: { gravity: 2, judgment: 1 } }, { text: "一刹那之间：精准地切入关键节点", traits: { time: 2, thunder: 1 } }, { text: "对方的心：让他自己看见最害怕的东西", traits: { judgment: 2, gravity: 1 } },
  ] },
  { eyebrow: "06 / 血之选择", title: "力量越强，反噬越重。你会怎么使用它？", answers: [
    { text: "只在必须保护某个人时使用", traits: { gravity: 1, judgment: 2 } }, { text: "控制在可预测范围内，慢慢逼近极限", traits: { time: 2, gravity: 1 } }, { text: "既然已经选择，就不留后手", traits: { fire: 2, thunder: 1 } }, { text: "先找到代价的来源，再决定是否承担", traits: { judgment: 2, time: 1 } },
  ] },
];

const profiles: Record<Trait, Omit<ResultProfile, "grade" | "gradeLabel" | "score" | "dominant">> = {
  fire: { spell: "君焰", spellNumber: "序列号 89", spellType: "火元素 · 高危攻击型", spellDescription: "你对直接、炽烈且有边界的力量有天然亲和。你的领域更像一座被压缩的熔炉：平时克制，释放时迅速改变战局。", character: "楚子航", characterTag: "狮心会 / 执行者", characterDescription: "沉默、精准、把失控锁在最后一秒之前。" },
  thunder: { spell: "雷池", spellNumber: "序列号 59", spellType: "雷元素 · 领域型", spellDescription: "你的力量倾向于制造高压环境，并在最短路径上完成决断。你不需要喧闹，真正的危险往往来自突然降临的那一下。", character: "凯撒·加图索", characterTag: "学生会 / 领队者", characterDescription: "强烈的自我意志，和在混乱中仍能保持仪式感的控制力。" },
  gravity: { spell: "王权", spellNumber: "序列号 91", spellType: "重力元素 · 控制型", spellDescription: "你擅长建立秩序，让周围的变量逐一沉降。你的强大不一定来自破坏，而来自让所有人意识到：规则已经改变。", character: "源稚生", characterTag: "日本分部 / 守门人", characterDescription: "背负传统与责任，在重压下仍努力保留人的形状。" },
  time: { spell: "时间零", spellNumber: "序列号 · 高阶领域", spellType: "时间元素 · 速度型", spellDescription: "你对节奏、缝隙和关键瞬间极其敏感。你不必成为最强的火力，只要比别人先半步，结果就已经改写。", character: "昂热", characterTag: "卡塞尔学院 / 校长", characterDescription: "把漫长岁月压缩成一记出鞘，果断而危险。" },
  judgment: { spell: "审判", spellNumber: "序列号 111", spellType: "雷电元素 · 终结型", spellDescription: "你对隐藏的真相与不可逆的选择有强烈感知。你的言灵不是为了炫耀力量，而像一道宣判：在它落下之前，所有人都有机会回头。", character: "绘梨衣", characterTag: "上杉家 / 红发巫女", characterDescription: "极高的纯度与破坏力，被安静地藏在近乎透明的情感里。" },
};
const traitLabels: Record<Trait, string> = { fire: "火元素亲和", thunder: "雷元素亲和", gravity: "重力控制", time: "时间感知", judgment: "审判意志" };
function rankForScore(score: number) { if (score >= 33) return { grade: "S", gradeLabel: "龙王级潜势" }; if (score >= 29) return { grade: "A", gradeLabel: "极高危血统" }; if (score >= 25) return { grade: "B", gradeLabel: "高危血统" }; if (score >= 21) return { grade: "C", gradeLabel: "稳定觉醒血统" }; if (score >= 18) return { grade: "D", gradeLabel: "低显性血统" }; if (score >= 15) return { grade: "E", gradeLabel: "微弱血统回响" }; return { grade: "F", gradeLabel: "未觉醒倾向" }; }
function calculateResult(answers: number[]): ResultProfile {
  const scores: Record<Trait, number> = { fire: 0, thunder: 0, gravity: 0, time: 0, judgment: 0 };
  answers.forEach((answerIndex, questionIndex) => { const answer = questions[questionIndex]?.answers[answerIndex]; if (!answer) return; Object.entries(answer.traits).forEach(([trait, value]) => { scores[trait as Trait] += value ?? 0; }); });
  const dominant = (Object.keys(scores) as Trait[]).sort((a, b) => scores[b] - scores[a])[0] ?? "fire"; const score = Math.min(36, 12 + Object.values(scores).reduce((sum, value) => sum + value, 0));
  return { ...profiles[dominant], ...rankForScore(score), score, dominant };
}
function Emblem({ trait = "fire" }: { trait?: Trait }) { const Icon = trait === "fire" ? Flame : trait === "thunder" ? Zap : trait === "gravity" ? Shield : trait === "time" ? Wind : Stars; return <div className={`emblem emblem-${trait}`} aria-hidden="true"><Icon size={20} strokeWidth={1.5} /></div>; }

*/

export default function Home() {
  return <AssessmentPage />;
}

/*
  const [stage, setStage] = useState<"intro" | "quiz" | "result">("intro"); const [questionIndex, setQuestionIndex] = useState(0); const [answers, setAnswers] = useState<number[]>([]); const [selected, setSelected] = useState<number | null>(null); const [name, setName] = useState(""); const [ageRange, setAgeRange] = useState(""); const [location, setLocation] = useState(""); const [showMethodology, setShowMethodology] = useState(false); const [showLibrary, setShowLibrary] = useState(false); const [libraryQuery, setLibraryQuery] = useState(""); const [libraryFamily, setLibraryFamily] = useState<(typeof SPELL_FAMILIES)[number]>("全部");
  const result = useMemo(() => calculateResult(answers), [answers]); const currentQuestion = questions[questionIndex]; const quizProgress = Math.round(((questionIndex + (selected !== null ? 1 : 0)) / questions.length) * 100); const filteredSpells = useMemo(() => SPELLS.filter((spell) => (libraryFamily === "全部" || spell.family === libraryFamily) && [spell.name, spell.serial, spell.category, spell.holder].join(" ").toLowerCase().includes(libraryQuery.trim().toLowerCase())), [libraryFamily, libraryQuery]);
  useEffect(() => { const modelContext = typeof document !== "undefined" ? document.modelContext : undefined; if (!modelContext?.registerTool) return; const controller = new AbortController(); void Promise.resolve(modelContext.registerTool({ name: "start_dragon_heritage_test", title: "开始龙族血统测试", description: "开始一次新的龙族血统与言灵匹配测试，并清空当前进度。", inputSchema: { type: "object", properties: {}, additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute() { setStage("quiz"); setQuestionIndex(0); setAnswers([]); setSelected(null); return { status: "started", questionCount: questions.length }; } }, { signal: controller.signal })).catch(() => undefined); return () => controller.abort(); }, []);
  const startQuiz = () => { setStage("quiz"); setQuestionIndex(0); setAnswers([]); setSelected(null); };
  const nextQuestion = () => { if (selected === null) return; const nextAnswers = [...answers]; nextAnswers[questionIndex] = selected; setAnswers(nextAnswers); if (questionIndex === questions.length - 1) { setStage("result"); return; } setQuestionIndex((index) => index + 1); setSelected(nextAnswers[questionIndex + 1] ?? null); };
  const reset = () => { setStage("intro"); setQuestionIndex(0); setAnswers([]); setSelected(null); };
  return <main className="app-shell"><div className="grain" aria-hidden="true" />
    <header className="topbar"><div className="brand-lockup"><div className="brand-mark" aria-hidden="true"><span>ᛉ</span></div><div><p className="brand-kicker">CASSel archive / 0.5</p><p className="brand-name">龙族血统测试局</p></div></div><div className="topbar-actions"><button className="method-link" onClick={() => setShowLibrary(true)}><Database size={16} /><span>言灵库 · {SPELLS.length}</span></button><button className="method-link" onClick={() => setShowMethodology(true)}><BookOpen size={16} /><span>设定依据</span></button></div></header>
    <div className="layout-grid"><aside className="left-rail" aria-label="测试说明"><div className="rail-caption">ARCHIVE NOTE</div><div className="rail-line" /><p>以公开资料整理的言灵序列与角色倾向为参考，生成一份属于你的混血种档案。</p><div className="rail-stamp">NO. 001 / PERSONAL</div></aside>
      <section className="main-panel">
        {stage === "intro" && <div className="intro-view fade-in"><div className="intro-copy"><div className="status-chip"><span className="status-dot" />档案接口已就绪</div><p className="section-kicker">THE DRAGON HERITAGE INDEX</p><h1>你的血统，<br /><em>会说出什么？</em></h1><p className="intro-lede">六道问题，测出你的血统潜势、元素亲和，以及最可能觉醒的言灵。</p><div className="intro-stats"><span><strong>06</strong> 道题目</span><span><strong>05</strong> 类倾向</span><span><strong>01</strong> 份档案</span></div><div className="profile-fields"><label><span>档案称呼</span><input value={name} onChange={(event) => setName(event.target.value)} placeholder="例如：路明非" /></label><label><span>年龄段</span><select value={ageRange} onChange={(event) => setAgeRange(event.target.value)}><option value="">选择</option><option>18 岁以下</option><option>18–24 岁</option><option>25–34 岁</option><option>35 岁以上</option></select></label><label><span>所在城市</span><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="可选" /></label></div><button className="primary-button" onClick={startQuiz}>开始测试 <ArrowRight size={18} /></button><p className="microcopy">个人信息仅用于生成本次档案 · 预计用时 2 分钟</p></div><div className="intro-instrument" aria-label="言灵序列表视觉示意"><div className="instrument-glow" /><div className="instrument-ring ring-outer" /><div className="instrument-ring ring-mid" /><div className="instrument-core"><Sparkles size={27} /><span>言灵<br />序列</span></div><div className="instrument-label label-top">血统浓度 <strong>—</strong></div><div className="instrument-label label-right">元素回响 <strong>—</strong></div><div className="instrument-label label-bottom">言灵适配 <strong>—</strong></div><div className="instrument-label label-left">龙文识别 <strong>—</strong></div></div></div>}
        {stage === "quiz" && currentQuestion && <div className="quiz-view fade-in"><div className="quiz-head"><div><p className="section-kicker">PERSONAL FILE / {String(questionIndex + 1).padStart(2, "0")}</p><div className="progress-track"><span style={{ width: `${Math.max(10, quizProgress)}%` }} /></div></div><span className="progress-label">{String(questionIndex + 1).padStart(2, "0")} / {String(questions.length).padStart(2, "0")}</span></div><div className="question-block"><p className="question-eyebrow">{currentQuestion.eyebrow}</p><h1>{currentQuestion.title}</h1>{currentQuestion.note && <p className="question-note">{currentQuestion.note}</p>}<div className="answer-list" role="radiogroup" aria-label={currentQuestion.title}>{currentQuestion.answers.map((answer, index) => <button className={`answer-card ${selected === index ? "is-selected" : ""}`} key={answer.text} onClick={() => setSelected(index)} role="radio" aria-checked={selected === index}><span className="answer-index">{String.fromCharCode(65 + index)}</span><span>{answer.text}</span><ChevronRight className="answer-arrow" size={18} /></button>)}</div></div><div className="quiz-actions"><button className="back-button" onClick={() => questionIndex === 0 ? setStage("intro") : (setQuestionIndex((index) => index - 1), setSelected(answers[questionIndex - 1] ?? null))}><ArrowLeft size={17} /> 上一题</button><button className="primary-button compact" disabled={selected === null} onClick={nextQuestion}>{questionIndex === questions.length - 1 ? "查看档案" : "下一题"} <ArrowRight size={17} /></button></div></div>}
        {stage === "result" && <div className="result-view fade-in"><div className="result-topline"><span>PERSONAL FILE / COMPLETE</span><span>ARCHIVE 05 · 2026</span></div><div className="result-hero"><div><p className="section-kicker">{name ? `${name} 的测试档案` : "你的测试档案"}</p><h1>血统评级 <span>{result.grade}</span></h1><p className="result-label">{result.gradeLabel} <span>·</span> {result.grade === "F" ? "觉醒倾向较弱" : "觉醒倾向已确认"}</p></div><div className="result-seal"><BadgeCheck size={22} /><span>CASSEL<br />VERIFIED</span></div></div><div className="result-grid"><div className="result-card spell-card"><div className="card-heading"><span>PRIMARY SPIRIT</span><span>{result.spellNumber}</span></div><div className="spell-display"><Emblem trait={result.dominant} /><div><h2>{result.spell}</h2><p>{result.spellType}</p></div></div><p className="card-description">{result.spellDescription}</p><div className="meter-row"><span>适配度</span><div className="meter"><span style={{ width: `${Math.min(96, 72 + result.score / 2)}%` }} /></div><strong>{Math.min(96, 72 + Math.round(result.score / 2))}%</strong></div></div><div className="result-card character-card"><div className="card-heading"><span>RESONANT PROFILE</span><span>ROLE MATCH</span></div><p className="match-caption">最接近你的角色气质</p><h2>{result.character}</h2><p className="character-tag">{result.characterTag}</p><p className="card-description">{result.characterDescription}</p><div className="trait-chip"><Sparkles size={14} /> {traitLabels[result.dominant]}</div></div></div><div className="identity-strip"><div><span>血统潜势</span><strong>{result.score} <small>/ 36</small></strong></div><div><span>主要亲和</span><strong>{traitLabels[result.dominant]}</strong></div><div><span>档案编号</span><strong>DRG-{String(result.score).padStart(3, "0")}</strong></div></div><div className="result-footer"><p><CircleHelp size={16} /> 本结果是基于公开设定整理的角色化推演，不代表官方认证。</p><button className="back-button" onClick={reset}><RotateCcw size={16} /> 重新测试</button></div></div>}
      </section>
      <aside className="right-rail" aria-label="五部小说参考"><div className="rail-caption">THE CHRONICLES</div><div className="book-stack">{["Ⅰ 火之晨曦", "Ⅱ 悼亡者之瞳", "Ⅲ 黑月之潮", "Ⅳ 奥丁之渊", "Ⅴ 悼亡者的归来"].map((book, index) => <div className={`book book-${index + 1}`} key={book}><span>{book}</span><i /></div>)}</div><p className="right-note">五部正传中出现过的言灵与人物倾向，被整理成这份测试的灵感索引。</p></aside>
    </div><footer className="footer-bar"><span>© DRAGON HERITAGE INDEX</span><span>非官方粉丝向体验 · 仅供娱乐</span></footer>
    {showMethodology && <div className="modal-backdrop" role="presentation" onClick={() => setShowMethodology(false)}><div className="method-modal" role="dialog" aria-modal="true" aria-labelledby="method-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setShowMethodology(false)} aria-label="关闭"><X size={18} /></button><p className="section-kicker">REFERENCE NOTE / 001</p><h2 id="method-title">设定依据与使用说明</h2><p>本测试参考《龙族》正传五部中出现的言灵名称、序列号、能力倾向和角色行为气质，抽象成“元素亲和 + 意志选择 + 领域偏好”的体验式评分。</p><div className="method-list"><div><span>01</span><p>言灵名称与角色匹配，取自公开世界观资料的整理。</p></div><div><span>02</span><p>评级是为了让问卷结果更有代入感，不等同于原作中的血统检测。</p></div><div><span>03</span><p>后续可继续扩充言灵序列表、角色卡、分支题和来源标注。</p></div></div><button className="primary-button compact" onClick={() => setShowMethodology(false)}>了解，开始探索 <ArrowRight size={17} /></button></div></div>}
    {showLibrary && <div className="modal-backdrop" role="presentation" onClick={() => setShowLibrary(false)}><div className="library-modal" role="dialog" aria-modal="true" aria-labelledby="library-title" onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setShowLibrary(false)} aria-label="关闭"><X size={18} /></button><div className="library-heading"><div><p className="section-kicker">ARCHIVE / SPELL INDEX</p><h2 id="library-title">言灵档案库 <span>{filteredSpells.length} / {SPELLS.length}</span></h2></div><p>已收录正传相关的已知序列、公开整理和未定序列名称。</p></div><div className="library-controls"><label className="library-search"><Search size={16} /><input value={libraryQuery} onChange={(event) => setLibraryQuery(event.target.value)} placeholder="搜索言灵、角色或属性" /></label><select value={libraryFamily} onChange={(event) => setLibraryFamily(event.target.value as (typeof SPELL_FAMILIES)[number])}>{SPELL_FAMILIES.map((family) => <option key={family}>{family}</option>)}</select></div><div className="spell-library-grid">{filteredSpells.map((spell) => <article className="spell-index-card" key={spell.name + "-" + spell.serial}><div className="spell-card-top"><span className="spell-serial">{spell.serial}</span><span className={"spell-confidence confidence-" + (spell.confidence === "已知序列" ? "known" : spell.confidence === "公开整理" ? "public" : "unknown")}>{spell.confidence}</span></div><h3>{spell.name}</h3><p className="spell-meta">{spell.family} · {spell.category}</p><p>{spell.summary}</p><div className="spell-card-bottom"><span>{spell.holder}</span><strong>{spell.danger}</strong></div></article>)}</div>{filteredSpells.length === 0 && <div className="library-empty">没有找到匹配的言灵档案。</div>}</div></div>}
  </main>;
}*/
